name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Repo “Variables” (Settings → Secrets and variables → Actions → Variables)
    env:
      SSH_HOST: ${{ vars.SSH_HOST }}          # e.g. 64.23.198.220
      SSH_PORT: ${{ vars.SSH_PORT }}          # e.g. 22
      SSH_USER: ${{ vars.SSH_USER }}          # e.g. deploy
      SERVICE_NAME: ${{ vars.SERVICE_NAME }}  # e.g. predictpix
      RSYNC_SRC: ${{ vars.RSYNC_SRC }}        # e.g. backend/
      RSYNC_DEST: ${{ vars.RSYNC_DEST }}      # e.g. /opt/predictpix/app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${SSH_PORT:-22}" -T 15 -H "${SSH_HOST}" >> ~/.ssh/known_hosts

      - name: Rsync app to server
        run: |
          rsync -az --delete \
            --omit-dir-times --no-perms --no-owner --no-group \
            -e "ssh -p ${SSH_PORT:-22}" \
            "${RSYNC_SRC:-backend/}" "${SSH_USER}@${SSH_HOST}:${RSYNC_DEST:-/opt/predictpix/app}"

      - name: Restart service
        run: |
          ssh -p "${SSH_PORT:-22}" "${SSH_USER}@${SSH_HOST}" \
            'sudo -n /usr/bin/systemctl restart '"${SERVICE_NAME}"' && sudo -n /usr/bin/systemctl is-active '"${SERVICE_NAME}"''

      - name: Health check
        run: curl -fsS https://predictpix.com/api/health
