name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${SSH_PORT:-22} -T 15 -H ${SSH_HOST} >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ vars.SSH_HOST }}
          SSH_PORT: ${{ vars.SSH_PORT }}

      - name: Rsync app to server
        run: |
          rsync -az --delete "${RSYNC_SRC:-app/}" "${SSH_USER}@${SSH_HOST}:${RSYNC_DEST:-/opt/predictpix/app}"
        env:
          SSH_HOST: ${{ vars.SSH_HOST }}
          SSH_USER: ${{ vars.SSH_USER }}
          RSYNC_SRC: ${{ vars.RSYNC_SRC }}
          RSYNC_DEST: ${{ vars.RSYNC_DEST }}

      - name: Restart service
        run: |
          ssh -p ${SSH_PORT:-22} ${SSH_USER}@${SSH_HOST} \
            'sudo systemctl restart '"${SERVICE_NAME}"' && sudo systemctl is-active '"${SERVICE_NAME}"
        env:
          SSH_HOST: ${{ vars.SSH_HOST }}
          SSH_USER: ${{ vars.SSH_USER }}
          SSH_PORT: ${{ vars.SSH_PORT }}
          SERVICE_NAME: ${{ vars.SERVICE_NAME }}

      - name: Health check
        run: curl -fsS https://predictpix.com/api/health
